export const ACCEPTED_EXTENSIONS = [
  "pdf", "docx", "doc", "pptx", "ppt", "odt", "rtf", "epub", "xml",
  "xls", "xlsx", "csv", "html", "htm", "txt", "md", "markdown", "rst",
  "jpg", "jpeg", "png", "tiff", "tif", "bmp", "webp", "gif",
] as const;

export const ACCEPT_ATTR = ACCEPTED_EXTENSIONS.map((e) => `.${e}`).join(",");

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10 MiB client-side default

export const TRACE_ID_RE = /^[0-9a-f]{32}$/;

/** Routes generated by the console itself, hidden by default in observability. */
export const CONSOLE_TRAFFIC_ROUTES = [
  "/health",
  "/traces",
  "/logs",
  "/metrics",
];

export const LOCALSTORAGE_KEYS = {
  theme: "rag-console:theme:v1",
  documents: "rag-console:documents:v1",
  selectedDocuments: "rag-console:selected-documents:v1",
  copilotHistory: "rag-console:copilot-history:v1",
  copilotConversation: "rag-console:copilot-conversation:v1",
  sqlLabHistory: "rag-console:sql-lab-history:v1",
  observability: "rag-console:observability-preferences:v1",
  authAccessToken: "rag-console:auth:access:v1",
  authRefreshToken: "rag-console:auth:refresh:v1",
} as const;

export const PIPELINE_STEPS = [
  "Queued",
  "Parsing",
  "Chunking",
  "Embedding",
  "Indexed",
] as const;

export type PipelineStep = (typeof PIPELINE_STEPS)[number];
